services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - LANGFLOW_CONFIG_DIR=app/langflow
    volumes:
      - langflow-data:/app/langflow
    networks:
      - langflow_internal_net # <-- Use new network name

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - langflow_internal_net # <-- Use new network name

volumes:
  langflow-postgres:
  langflow-data:

# Define the explicit network with a NEW name and desired subnet
networks:
  langflow_internal_net: # <-- New network name
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.17.0/24 # <-- Keep your chosen subnet
          # gateway: 10.21.15.1
